import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

serve(async (req) => {
  try {
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    const { user_id, month, year } = await req.json();

    if (!user_id || !month || !year) {
      return new Response(
        JSON.stringify({ error: 'user_id, month, year required' }),
        { status: 400, headers: { 'Content-Type': 'application/json' } }
      );
    }

    // Get user profile
    const { data: user } = await supabase
      .from('users')
      .select('full_name, phone, state, district')
      .eq('id', user_id)
      .single();

    // Get expense summary
    const { data: summary } = await supabase
      .rpc('get_expense_summary', {
        p_user_id: user_id,
        p_month: month,
        p_year: year,
      });

    // Get itemised expenses
    const monthStr = String(month).padStart(2, '0');
    const nextMonth = String(month + 1).padStart(2, '0');
    const { data: expenses } = await supabase
      .from('expense_records')
      .select('*')
      .eq('user_id', user_id)
      .gte('recorded_date', `${year}-${monthStr}-01`)
      .lt('recorded_date', `${year}-${nextMonth}-01`)
      .order('recorded_date', { ascending: true });

    const totalAmount = (summary ?? []).reduce(
      (sum: number, item: any) => sum + Number(item.total_amount), 0
    );

    // Generate HTML report
    const monthNames = [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December'
    ];

    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body { font-family: Arial, sans-serif; padding: 20px; color: #333; }
    h1 { color: #2D7A3A; }
    .header { border-bottom: 2px solid #2D7A3A; padding-bottom: 10px; margin-bottom: 20px; }
    .total { background: #f0f9f0; padding: 15px; border-radius: 8px; margin: 20px 0; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th { background: #2D7A3A; color: white; padding: 10px; text-align: left; }
    td { padding: 8px 10px; border-bottom: 1px solid #eee; }
    tr:nth-child(even) { background: #f9f9f9; }
    .footer { margin-top: 30px; font-size: 12px; color: #666; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🌾 KrishiSahayak - Expense Report</h1>
    <p><strong>Farmer:</strong> ${user?.full_name ?? 'N/A'}</p>
    <p><strong>Period:</strong> ${monthNames[month - 1]} ${year}</p>
    <p><strong>State:</strong> ${user?.state ?? 'N/A'}</p>
  </div>

  <div class="total">
    <h2>Total Expenses: ₹${totalAmount.toLocaleString('en-IN')}</h2>
  </div>

  <h3>Category Summary</h3>
  <table>
    <tr>
      <th>Category</th>
      <th>Transactions</th>
      <th>Total Amount</th>
    </tr>
    ${(summary ?? []).map((item: any) => `
    <tr>
      <td>${item.category}</td>
      <td>${item.transaction_count}</td>
      <td>₹${Number(item.total_amount).toLocaleString('en-IN')}</td>
    </tr>
    `).join('')}
  </table>

  <h3>Itemised Expenses (${(expenses ?? []).length} records)</h3>
  <table>
    <tr>
      <th>Date</th>
      <th>Category</th>
      <th>Description</th>
      <th>Payment</th>
      <th>Amount</th>
    </tr>
    ${(expenses ?? []).map((exp: any) => `
    <tr>
      <td>${exp.recorded_date}</td>
      <td>${exp.category}</td>
      <td>${exp.description ?? '-'}</td>
      <td>${exp.payment_method}</td>
      <td>₹${Number(exp.amount).toLocaleString('en-IN')}</td>
    </tr>
    `).join('')}
  </table>

  <div class="footer">
    <p>Generated by KrishiSahayak on ${new Date().toLocaleDateString('en-IN')}</p>
  </div>
</body>
</html>`;

    return new Response(
      JSON.stringify({
        success: true,
        html,
        summary: {
          total: totalAmount,
          records: (expenses ?? []).length,
          month: monthNames[month - 1],
          year,
        },
      }),
      { headers: { 'Content-Type': 'application/json' } }
    );
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    return new Response(
      JSON.stringify({ error: message }),
      { status: 500, headers: { 'Content-Type': 'application/json' } }
    );
  }
});